import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Source_Sans_3, Roboto, Khand } from "next/font/google";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";


const sans = Source_Sans_3({
    variable: "--font-sans",
    subsets: ["latin"],
    weight: ["300", "400", "700"],
});

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
});

const khand = Khand({
    variable: "--font-khand",
    subsets: ["latin"],
    weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Los Tres Gudinos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth" data-scroll-behavior="smooth">
        {/* background: linear-gradient(rgba(0,0,0,.6), rgba(0,0,0,.6)), url(bg.jpg) center / cover fixed; */}
      <body className={cn(sans.className, roboto.variable, khand.variable)}>
        <SiteHeader />
        <main>{children}</main>
        <SiteFooter />
      </body>
    </html>
  );
}

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", figtree.variable)}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
